### ISSUE TITLE
Print version different from the editor version

### ISSUE THREAD

**Issue by jcavat** [ABAPlan/abaplan-core#73]

**Comment by jcavat** [comment]
![img1](https://cloud.githubusercontent.com/assets/1701806/23861917/d4515024-080b-11e7-8acd-5e7eadb10c7d.jpg)

![img2](https://cloud.githubusercontent.com/assets/1701806/23861920/d7ae6e6e-080b-11e7-83a0-e20a6f795262.jpg)

Any idea ?

**Comment by jcavat** [comment]
And the limit of the map is different. Any idea ?

**Comment by JohnerPierre** [comment]
For the limit it's a mistake from me in the CSS (i change the size of the contener of the map instead of the map directly)

For the change of map it can be some hidden svg balise ( it's react strangly with CSS and bootstrap) but i need to test.

Can i have the location for my debugging ? 

Thanks in advance and sorry for the mistakes

**Comment by jcavat** [comment]
No problem. Look for 'Centre de Geneve'. I don't remember the id. Maybe 6 or 8.

**Comment by jcavat** [comment]
Try to keep the same ratio and the same size for the div map.

**Comment by jcavat** [comment]
Textures issues come from another bug. See #74. Keep looking the size-ratio issue.

**Comment by jcavat** [comment]
But not very precise. Maybe the student's contribution fix that problem. See new issue #77.
